# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Create symbolic link for ecosystem.config.js
        run: ln -sf /etc/pm2configs/orpheusnet/ecosystem.config.js /home/leon/projects/orpheusnet/_work/orpheusnet-backend/orpheusnet-backend/ecosystem.config.js

      - name: Start or restart pm2 process with ecosystem config
        run: pm2 start ecosystem.config.js --env production || pm2 reload ecosystem.config.js --update-env
        working-directory: /home/leon/projects/orpheusnet/_work/orpheusnet-backend/orpheusnet-backend

      - name: Save pm2 process list
        run: pm2 save
        working-directory: /home/leon/projects/orpheusnet/_work/orpheusnet-backend/orpheusnet-backend
